version: 2

models:
  - name: dim_comics
    description: "Dimension table containing XKCD comics metadata"
    columns:
      - name: comic_id
        description: "Unique ID of the comic"
        tests:
          - unique
          - not_null
      - name: title
        description: "Title of the comic"
        tests:
          - not_null

  - name: fact_comic_views
    description: "Fact table tracking XKCD comic views, cost, and ratings"
    columns:
      - name: comic_id
        description: "FK reference to dim_comics"
        tests:
          - relationships:
              to: ref('dim_comics')
              field: comic_id

      - name: cost
        description: "Cost associated with viewing the comic"
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 1  # Ensures cost is always greater than 0
              max_value: 10000  # Adjust based on expected cost range

      - name: views
        description: "Number of times a comic has been viewed"
        tests:
          - dbt_expectations.expect_column_values_to_be_increasing  # Views should always increase

      - name: review_score
        description: "User review rating of the comic (1-10)"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 1
              max_value: 10
