Transformation:
  outputs:
    dev:
      dbname: xkcd_db
      host: localhost
      pass: your password
      port: 5432
      schema: xkcd_db
      threads: 1
      type: postgres
      user: your username
  target: dev



